service: ws-carddraw

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-southeast-2
  stage: dev
  websocketsApiRouteSelectionExpression: $request.body.action

  iamRoleStatements:
    - Effect: Allow
      Action:
        - "execute-api:ManageConnections"
      Resource:
        - "arn:aws:execute-api:*:*:**/@connections/*"
    - Effect: Allow
      Action:
        - "dynamodb:PutItem"
        - "dynamodb:GetItem"
        - "dynamodb:DeleteItem"
        - "dynamodb:Query"
        - "dynamodb:Scan"
      Resource:
        - Fn::GetAtt: [connectionTable, Arn]
        - Fn::Join:
            - '/'
            - - Fn::GetAtt: [connectionTable, Arn]
              - '*'

  environment:
    TABLE_NAME: ${self:custom.TABLE_NAME}

custom:
  TABLE_NAME: "carddraw"

functions:
  handler:
    handler: websocket.handler
    events:
      - websocket: $connect
      - websocket: $disconnect
      - websocket: $default
      - websocket: sendmessage
      - websocket: info

resources:
  Resources:
    connectionTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
        - AttributeName: connectionId
          AttributeType: "S"
        KeySchema:
        - AttributeName: "connectionId"
          KeyType: "HASH"
        BillingMode: "PAY_PER_REQUEST"
        SSESpecification:
          SSEEnabled: True
        TableName: ${self:custom.TABLE_NAME}